name: C/C++ CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create_config_file
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp -f defconfig/mt7981-ax3000.config .config
        make menuconfig
        make -j$(nproc)
